// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: proto/pair.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PairMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login        string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	PasswordHash string `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Metadata     string `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *PairMsg) Reset() {
	*x = PairMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairMsg) ProtoMessage() {}

func (x *PairMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairMsg.ProtoReflect.Descriptor instead.
func (*PairMsg) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{0}
}

func (x *PairMsg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PairMsg) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PairMsg) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *PairMsg) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CreatePairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Pair  *PairMsg `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *CreatePairRequest) Reset() {
	*x = CreatePairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePairRequest) ProtoMessage() {}

func (x *CreatePairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePairRequest.ProtoReflect.Descriptor instead.
func (*CreatePairRequest) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePairRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreatePairRequest) GetPair() *PairMsg {
	if x != nil {
		return x.Pair
	}
	return nil
}

type CreatePairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair  *PairMsg `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Error string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreatePairResponse) Reset() {
	*x = CreatePairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePairResponse) ProtoMessage() {}

func (x *CreatePairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePairResponse.ProtoReflect.Descriptor instead.
func (*CreatePairResponse) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePairResponse) GetPair() *PairMsg {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *CreatePairResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetPairRequest) Reset() {
	*x = GetPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairRequest) ProtoMessage() {}

func (x *GetPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairRequest.ProtoReflect.Descriptor instead.
func (*GetPairRequest) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{3}
}

func (x *GetPairRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*PairMsg `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	Error string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetPairResponse) Reset() {
	*x = GetPairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairResponse) ProtoMessage() {}

func (x *GetPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairResponse.ProtoReflect.Descriptor instead.
func (*GetPairResponse) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{4}
}

func (x *GetPairResponse) GetPairs() []*PairMsg {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *GetPairResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdatePairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair *PairMsg `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *UpdatePairRequest) Reset() {
	*x = UpdatePairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePairRequest) ProtoMessage() {}

func (x *UpdatePairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePairRequest.ProtoReflect.Descriptor instead.
func (*UpdatePairRequest) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePairRequest) GetPair() *PairMsg {
	if x != nil {
		return x.Pair
	}
	return nil
}

type UpdatePairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair  *PairMsg `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Error string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdatePairResponse) Reset() {
	*x = UpdatePairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePairResponse) ProtoMessage() {}

func (x *UpdatePairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePairResponse.ProtoReflect.Descriptor instead.
func (*UpdatePairResponse) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePairResponse) GetPair() *PairMsg {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *UpdatePairResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeletePairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *DeletePairRequest) Reset() {
	*x = DeletePairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePairRequest) ProtoMessage() {}

func (x *DeletePairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePairRequest.ProtoReflect.Descriptor instead.
func (*DeletePairRequest) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePairRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeletePairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeletePairResponse) Reset() {
	*x = DeletePairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pair_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePairResponse) ProtoMessage() {}

func (x *DeletePairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pair_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePairResponse.ProtoReflect.Descriptor instead.
func (*DeletePairResponse) Descriptor() ([]byte, []int) {
	return file_proto_pair_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePairResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_pair_proto protoreflect.FileDescriptor

var file_proto_pair_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x07, 0x50, 0x61, 0x69,
	0x72, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4d, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69,
	0x72, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0x4e, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x04,
	0x70, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x4d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69,
	0x72, 0x4d, 0x73, 0x67, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x37, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69,
	0x72, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0x4e, 0x0a, 0x12, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x04,
	0x70, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x29, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2a, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0x89, 0x02, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a,
	0x28, 0x47, 0x6f, 0x70, 0x68, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_pair_proto_rawDescOnce sync.Once
	file_proto_pair_proto_rawDescData = file_proto_pair_proto_rawDesc
)

func file_proto_pair_proto_rawDescGZIP() []byte {
	file_proto_pair_proto_rawDescOnce.Do(func() {
		file_proto_pair_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pair_proto_rawDescData)
	})
	return file_proto_pair_proto_rawDescData
}

var file_proto_pair_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_pair_proto_goTypes = []interface{}{
	(*PairMsg)(nil),            // 0: proto.PairMsg
	(*CreatePairRequest)(nil),  // 1: proto.CreatePairRequest
	(*CreatePairResponse)(nil), // 2: proto.CreatePairResponse
	(*GetPairRequest)(nil),     // 3: proto.GetPairRequest
	(*GetPairResponse)(nil),    // 4: proto.GetPairResponse
	(*UpdatePairRequest)(nil),  // 5: proto.UpdatePairRequest
	(*UpdatePairResponse)(nil), // 6: proto.UpdatePairResponse
	(*DeletePairRequest)(nil),  // 7: proto.DeletePairRequest
	(*DeletePairResponse)(nil), // 8: proto.DeletePairResponse
}
var file_proto_pair_proto_depIdxs = []int32{
	0, // 0: proto.CreatePairRequest.pair:type_name -> proto.PairMsg
	0, // 1: proto.CreatePairResponse.pair:type_name -> proto.PairMsg
	0, // 2: proto.GetPairResponse.pairs:type_name -> proto.PairMsg
	0, // 3: proto.UpdatePairRequest.pair:type_name -> proto.PairMsg
	0, // 4: proto.UpdatePairResponse.pair:type_name -> proto.PairMsg
	1, // 5: proto.Pair.CreatePair:input_type -> proto.CreatePairRequest
	3, // 6: proto.Pair.GetPair:input_type -> proto.GetPairRequest
	5, // 7: proto.Pair.UpdatePair:input_type -> proto.UpdatePairRequest
	7, // 8: proto.Pair.DeletePair:input_type -> proto.DeletePairRequest
	2, // 9: proto.Pair.CreatePair:output_type -> proto.CreatePairResponse
	4, // 10: proto.Pair.GetPair:output_type -> proto.GetPairResponse
	6, // 11: proto.Pair.UpdatePair:output_type -> proto.UpdatePairResponse
	8, // 12: proto.Pair.DeletePair:output_type -> proto.DeletePairResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_pair_proto_init() }
func file_proto_pair_proto_init() {
	if File_proto_pair_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pair_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pair_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pair_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pair_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pair_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pair_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pair_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pair_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pair_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pair_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pair_proto_goTypes,
		DependencyIndexes: file_proto_pair_proto_depIdxs,
		MessageInfos:      file_proto_pair_proto_msgTypes,
	}.Build()
	File_proto_pair_proto = out.File
	file_proto_pair_proto_rawDesc = nil
	file_proto_pair_proto_goTypes = nil
	file_proto_pair_proto_depIdxs = nil
}
